### ISSUE TITLE
Vuex / Computed Prop

### ISSUE THREAD

**Issue by cannap** [declandewet/vue-meta#10]
Hi, 

What is the best way to get the title from a Vuex getter?

Current problem is my Title is not the same as in the Post on the page first after a F5 Refresh the title is correct 

```html
<template>
    <article class="single-post" v-if="post">
        <header class="post-header">
            <h1> {{post.title}} </h1>
        </header>
        <section v-html="post.content_html" class="post-content">
        </section>
    </article>
</template>
```

Also the title in post.title != my title in metaInfo but its should i dont know its a problem because async

```js
  name: 'SinglePost',
        computed: {
            post() {
                var post = this.$store.getters.getPost
                return post;
            }
        },
        metaInfo: {
            // if no subcomponents specify a metaInfo.title, this title will be used
            title () {
                    return this.post.title 
//The title is not the same as on the page the title is from the last visited page 
            }
        },
        data() {
            return {
                post: {}
            }
        },
        preFetch: function (store) {
            return store.dispatch('singlePost', store.state.route.params.slug)
        },
        mounted() {

            this.$store.dispatch('singlePost', this.$store.state.route.params.slug)

        },

    }
```

When i use in Simple Components works fine 

//E maybe the problem is from my side how i handle Switching the post

Problem is it updates not all the time when i console.log out in the metaInfo i see its just hits on the first load and not when switchting between my posts

```js
{
          path: ':slug',
          component: SinglePost,
          meta: {
            bodyClass: 'light',
          }
```
Or its something like  #9 

sry my english is not so good

**Comment by declandewet** [comment]
Thanks for the report @cannap - it seems as if this **is** related to #9. I will have a look at it tomorrow (its night time here)

**Comment by declandewet** [comment]
Hi @cannap!

I submitted a fix for this in https://github.com/declandewet/vue-meta/commit/6ad56ec73e428316c2e4c115274ca655024c2810

I also put together [an example](https://github.com/declandewet/vue-meta/blob/master/examples/vuex/app.js) for you to look at on how to use Vuex getters.

**Comment by cannap** [comment]
Hi, is this already on npm? or should i just use the github version and compile by my self

**Comment by declandewet** [comment]
@cannap it's not on NPM yet because it's not what I would consider stable enough to be released :wink: - use the github version for now, and make sure it's not in your Webpack excludes

**Comment by cannap** [comment]
Hi, yes i updated via github and checked the example
when the action is async 
```js
  actions: {
    getPost ({ commit }, payload) {
       setTimeout(() => {
          commit('getPost', payload)
       },2000)
    }
  }
```

same problem

**Comment by declandewet** [comment]
@cannap Ah! I see what you mean! I'll have a look at it tonight. Getting a fix in for this will be tricky, though.

**Comment by cannap** [comment]
good i cant wait to use this thing 🗡 i waited since vue 2.0 for something like this 🗡  because i had no idea how to make my own my first solution was reading the store on server but this was ugly

**Comment by declandewet** [comment]
Same - I'm building it because I'm _really_ going to need something like it soon :D

**Comment by declandewet** [comment]
@cannap - the "fix" has landed! :tada: https://github.com/declandewet/vue-meta/commit/076832cbd6b2ffcc804fcdb2a9edd438c58573b5

You can check out this example to see how handling async actions is done: https://github.com/declandewet/vue-meta/tree/076832cbd6b2ffcc804fcdb2a9edd438c58573b5/examples/vuex-async
