### ISSUE TITLE
Allow to specify a limit for <title> text length, truncate if above

### ISSUE THREAD

**Issue by jeerbl** [declandewet/vue-meta#100]
Hi,

It would be nice to have a way to specify a limit for the text length in the `title` tag. If the title length is greater than the limit, it would truncate the part before the `titleTemplate` string.

__Example__
Let's say you have:
```
title: 'Your page example is brought to you by the example company',
titleTemplate: '%s | Example Website'
```
If you specify the limit to 50, which this text exceeds, the computed title would be:

> Your page example is brought ... | Example Website

which is 50 characters long.

It would definitely be a nice-to-have feature for handling title lengths with Google limitations.

Cheers,
Jerome

**Comment by AlbinoDrought** [comment]
Now possible with a function `titleTemplate` (v1.2.0), although it does look a little dirty:

```js
const suffix = ' | Example Website';
const suffixLength = suffix.length;
const maxTitleLength = 50;
const maxChunkLength = maxTitleLength - suffixLength;

metaInfo: {
    titleTemplate: (chunk) => {
        const truncatedChunk = chunk.length > maxChunkLength ? `${chunk.substr(0, maxChunkLength - 3)}...` : chunk;
        return `${truncatedChunk}${suffix}`;
    },
},
```

Resulting title:

>Your page example is brought ... | Example Website

**Comment by jeerbl** [comment]
Nice thanks!
