### ISSUE TITLE
titleTemplate should take a function

### ISSUE THREAD

**Issue by homerjam** [declandewet/vue-meta#109]
Ideally I'd like to be able to determine whether or not to place dividers in the title (eg. pipes or hyphens).

```js
titleTemplate: (titleChunk) => {
  // If undefined or blank then we don't need the hyphen
  return titleChunk ? `${titleChunk} - Site Title` : 'Site Title';
}
```

**Comment by Atinux** [comment]
Hi @homerjam 

This should be backward compatible as well, any PR is welcome :)
