### ISSUE TITLE
How to use vue-meta with ssr?

### ISSUE THREAD

**Issue by romanrei** [declandewet/vue-meta#114]
Is there any way to use it with createBundleRenderer ? this function outputs the ssr bundle with html and then i'm using this html in .renderToString() function.
So when i'm adding ${meta.text()} to the res.send() my rendered html file becoming weird and not semantic. I mean meta tags are not in <head> and etc.

Thanks.

**Comment by romanrei** [comment]
I found a solution. if anyone interested just add {{{ meta.inject().title.text() }}} and other meta props in template.html

**Comment by andreasvirkus** [comment]
This works, however, the Vue SSR docs discourage the usage of `{{{ }}}` and warn us of potential XSS attacks:
> Use double-mustache (HTML-escaped interpolation) to avoid XSS attacks.

https://ssr.vuejs.org/en/head.html (See "Notes" at the bottom)

**Comment by romanrei** [comment]
I know this, but for now i don't know how to inject it to html. double mustaches just output it as text..

**Comment by newenegue** [comment]
Is there an alternative approach than using `{{{ }}}`?

**Comment by andreasvirkus** [comment]
@Atinux ping

**Comment by geekguy** [comment]
@Atinux - any update on @newenegue's previous comment?

**Comment by Atinux** [comment]
Actually, `meta.inject().title.text()` render escaped HTML so you can have to use `{{{ }}}`.

Example: `title: '<b>Coucou</b>'`

$meta().inject().title.text() => `<title data-vue-meta="true">&lt;b&gt;Coucou&lt;/b&gt;</title>`

**Comment by geekguy** [comment]
Oh, perfect.

Should we update this in doc?

**Comment by Atinux** [comment]
A PR would be awesome :)

**Comment by geekguy** [comment]
@Atinux - here you go - https://github.com/declandewet/vue-meta/pull/156
