### ISSUE TITLE
When specifying link in both parent and child you both arrays

### ISSUE THREAD

**Issue by Tazer** [declandewet/vue-meta#116]
I have a parent component that specifies an link array. 
Parent.vue
```
metaInfo(){
return { link: [{'rel: 'alternate',
            'hreflang': 'en',
            href: 'something'}]
}
}
``` 

Child.vue
```
metaInfo(){
return { link: [{'rel: 'alternate',
            'hreflang': 'en',
            href: 'override'}]
}
}
``` 

What I want todo is that the Child you override the Parent link array. But instead it's just appended. So I end up with both "something" and "override"

**Comment by Atinux** [comment]
Hi @Tazer 

You need to use the `vmid` property, please read https://github.com/declandewet/vue-meta#how-metainfo-is-resolved
