### ISSUE TITLE
Ability to use in a stand-alone component

### ISSUE THREAD

**Issue by andreasvirkus** [declandewet/vue-meta#121]
Hello, this is nothing critical, just something to consider for the future:
I'm using vue-meta in an SSR (Vue native, not nuxt) setup
and since we've got quite a lot of meta tags (necessary only for initial render),
then I've moved them out of the App.vue file into a separate component.

However, if I don't add empty `<template></template>` tags, Vue complains that
```
render function or template not defined in component: metaTags
```

If I do add the template tags, then Vue renders an empty div at the start of my app,
which is slightly disturbing and redundant in my eyes. `vue-head` for example
doesn't do this and allows you to have the metadata definition in a separate component.

If it's an easy fix, I'd like it to be considered. If not, just let me know so I could rest my heart
that it's out of my hands 😄 

Other than that, thanks for the only head-management plugin that plays well with SSR!

**Comment by Atinux** [comment]
Hi @andreasvirkus 

It works if your use the `render` method:

```js
Vue.component('my-headers', {
  render: (h) => h(),
  metaInfo: {
    title: 'My title'
  }
})
```

Vue will render a comment () DOM element :)

**Comment by andreasvirkus** [comment]
Yup, thanks. Achieved the same thing with `render() { return null }` but forgot to close the issue.
