### ISSUE TITLE
Something like bodyAttrs for head tag?

### ISSUE THREAD

**Issue by wilk** [declandewet/vue-meta#122]
Does exist something like this for the head tag?

https://github.com/declandewet/vue-meta#htmlattrs-object

In some situations, I need to add attributes to the head tag: for instance, namespaces for Open Graph -> https://developers.facebook.com/docs/reference/opengraph/object-type/article/

Best,
Wilk

**Comment by Atinux** [comment]
Will be available in 1.1 (released during the day)
