### ISSUE TITLE
changed() function in metaInfo returns Object with metaInfo instead of Vue instance

### ISSUE THREAD

**Issue by MDSLKTR** [declandewet/vue-meta#128]
Hey,

first of thanks for this great plugin! I have a question though. When using the changed function i currently have no way of telling my Vue Instance that metaInfo has in fact changed. In my current implementation as described in the docs it returns a simple object containing all meta data instead of the mounted Vue Instance. Is this behaviour intentended?

Vue Meta 1.0.5

```
   export default {
        props: {
            socialText: String,
            inverted: Boolean,
        },
        data() {
            return {
                url: window.location.origin,
                title: '',
                description: '',
                quote: '',
            };
        },

        metaInfo: {
            changed() {
                this.title = document.querySelector('meta[property="og:title"]').content;
                this.description = document.querySelector('meta[property="og:description"]').content;
                this.quote = document.querySelector('meta[property="share-text"]').content;


               // this returning itself instead of the vue instance
                console.log(this);
            },
        },
    };
```

Thanks in advance,
Simon

**Comment by Atinux** [comment]
Hi @MDSLKTR 

It's fixed with https://github.com/declandewet/vue-meta/commit/1acfa946debfee58c3fadb1fcad9e56927a235eb

I will release 1.1.0 today

**Comment by MDSLKTR** [comment]
Hi @Atinux,
great to hear! Thank you very much!
