### ISSUE TITLE
feature: add posibility to disable sanitize by tagIDKeyName value

### ISSUE THREAD

**Issue by pimlie** [declandewet/vue-meta#130]
At the moment it is only possible to disable sanitization for a whole meta group, it would be nice if you could disable it _per_ `tagIDKeyName` value as well.

A use case for this would be eg nuxt plugins. I have written a nuxt [module](https://github.com/pimlie/nuxt-piwik) that needs to define some javascript variables before including a source file. At the moment I can only do this by disabling sanitazion for all script tags. But with nuxt you can use quite a few modules from 3rd party sources and I have no idea what their requirements are. 

To make sure that you are not changing behaviour in other plugins, disabling sanitation for my script tag only would be nice. Something like:
```js
export default {
  metaInfo: {
    script: [
      { vmid: 'my-script', innerHTML: '{ "@context": "http://www.schema.org", "@type": "Organization" }', type: 'application/ld+json' }
    ],
     __dangerouslyDisableSanitizers: [ 'script:my-script' ],
    or
    __dangerouslyDisableSanitizers: {
      'script': [
        'my-script'
      ]
    }
  }
}
```

**Comment by iamdubx** [comment]
This is very good feature. +1
