### ISSUE TITLE
suitability for production use?

### ISSUE THREAD

**Issue by timcreatewell** [declandewet/vue-meta#131]
Hi there, sorry if this is the wrong place to ask this question - but I'm wondering, as the project is now at v1.1.0 is it still not suited for production use?

Thanks!

**Comment by edjroot** [comment]
Same question. The README says "[...] this project is still in very early alpha development [...]" but it doesn't seem like it. Looks like beta at worst. Am I wrong to assume it's already usable?

**Comment by Raiondesu** [comment]
@declandewet, people need answers! It's been 8 months already...

**Comment by jaredthirsk** [comment]
@declandewet @Atinux Any update on this?  Are certain simple usage scenarios apparently stable while others more experimental?  What concerns do you have about calling this "ready for production use" or "ready for beta testing"?

**Comment by Atinux** [comment]
I updated the README, vue-meta is ready for production since the 1.0 (it also been used in production for the last year).

I did not notice there were still a disclaimer.
