### ISSUE TITLE
Duplicate tag prevention

### ISSUE THREAD

**Issue by metekabak** [declandewet/vue-meta#143]
If I want a single og:title for example, i cant override it, it creates new one when calling from child component.

Do we have any method (uid) for that? or should i have done it via vuex or global mixin to override it?

Thanks

**Comment by makedonec88** [comment]
Hey @metekabak 

You should definitely check this part of README [How metaInfo is Resolved](https://github.com/declandewet/vue-meta#how-metainfo-is-resolved)

So in your case, you need to add `vmid` key ot each property, which should be unique:

**Before:**
```
{
  meta: [
    {  property: 'og:title', content: 'Not unique meta tag' }
  ]
}
```
**After:**
```
{
  meta: [
    { vmidL 'og:title', property: 'og:title', content: 'Super duper unique tag' }
  ]
}
```

More info in README

**Comment by seekingtheoptimal** [comment]
is there any real world case though when having duplicate meta tags is valid at all? the property itself should be the "vmid" by default I think
