### ISSUE TITLE
How to use vue-meta in Vue TypeScript's template?

### ISSUE THREAD

**Issue by koddr** [declandewet/vue-meta#144]
Hello. 

I'm using [vue-webpack-typescript](https://github.com/ducksoupdev/vue-webpack-typescript) template. But how to use your awesome plugin with it?

I already add to `./src/main.ts` this:

```
import Meta from 'vue-meta';

Vue.use(Meta, {
  keyName: 'metaInfo', 
  attribute: 'data-vue-meta', 
  ssrAttribute: 'data-vue-meta-ssr', 
  tagIDKeyName: 'vmid'
});
```

And add this to `./src/components/home/home.ts` component:

```
export class HomeComponent extends Vue {

  static metaInfo() {
    return {
      title: 'Test'
    }
  }

}
```

But this not working, don't show over written title.. Any help is welcome ;)

**Comment by martinschleiss** [comment]
hi @koddr ,

I had the same problem.
You have to declare the metaInfo function on the @ Component declaration of your vue component.

```
@Component({
    metaInfo() {
       return {
          title: "My awesome title"
      }
   }
})
export class AboutComponent extends Vue {
}
```

But doing this will probably yield an error because the @ Component declaration does not have a metaInfo field defined. Having used "vue-router" before I looked at their source code and you have to define something like this:

```
import Vue from "vue";

declare module "vue/types/options" {
    interface ComponentOptions<V extends Vue> {
        metaInfo?: any;
    }
}
```

**Comment by pengliheng** [comment]
I need to complete a component with `i18n`
```vue
@Component<HomePage>({
  i18n: {
    messages: {
      'zh-CN': zhCN,
      'zh-TW': zhTW,
      'en-US': enUS
    }
  },
  metaInfo: {
    title: (this as any).lang('title'),         // this not work....
    htmlAttrs: {
      lang: 'zh'
    },
    meta: [
      { charset: 'utf-8' },
      { name: 'keyword', content: 'home,page' },
      { name: 'description', content: 'Home 主页', vmid: 'test' },
      { name: 'viewport', content: 'width=device-width, initial-scale=2' }
    ]
  }
})
export default class HomePage extends Vue {
  public lang(key: string): VueI18n.TranslateResult {
    return this.$i18n.t(key);
  }
}
```

**Comment by ppulwey** [comment]
In case anybody is coming across this. I'm using it in Gridsome.
What @pengliheng and @martinschleiss are showing is correct. But it's only half of the work, if you want to use it with the data injected into your page.
I'm using the createPages hook in Gridsome to create pages and use the context property to inject data.
Also I use TypeScript with vue class compoentnts.

What I have done is to create a folder in root named "declarations". I've added @martinschleiss code here as 'vue-meta.ts':

```
import Vue from "vue";

declare module "vue/types/options" {
    interface ComponentOptions<V extends Vue> {
        metaInfo?: any;
    }
}
```

Then in your Vue Component file import this:
```
// ? Import this to extend the @Component decorator with metaInfo
import "@/declarations/vue-meta";
```

Your component then has to look like this:

```
@Component<Content>({
  metaInfo() {
    return {
      title: this.pageTitle,
      meta: [{ name: "author", content: "John Doe" }]
    };
  }
})
export default class Content extends Vue {
  // ? $context has to be defined here. Otherwise TypeScript complains about not existin variable
  public $context: any;

  private get pageTitle() {
    return this.$context.title;
  }
}
```

Your information from $context should show up as your page title now.

**Comment by MikeyBeLike** [comment]
Here's my solution, a bit hacky, but you get proper typing/autocomplete

I didn't have to create any extra .d.ts files or anything.

I created a getter/computed:
```  
get pageTitle () {
    if (this.courseData) {
      return this.courseData.page_title
    }
    return ''
}
```

then my component decorator looks a bit like this:

```
@Component({
  ...
  metaInfo: {
    title: (this as unknown as CourseIndex).pageTitle
  }
})
export default class CourseIndex extends Vue {
```

CourseIndex is my component class name, so it already has visibility to all of its properties/getters/methods

That's all

**Comment by ppulwey** [comment]
@MikeyBeLike  right. To have access to the this context of your component you should use your decorator like this:

 `@Component<CourseIndex>({...`

But TS compiler should complain about unknown property "metaInfo" in your decorator. That's why you have to declare this module.

**Comment by MikeyBeLike** [comment]
@ppulwey it didn't complain for me, it seems it was already typed, maybe check your version?

See here: https://github.com/nuxt/vue-meta/blob/master/types/vue.d.ts#L16

**Comment by stephane-poirier-umrsu** [comment]
For those stumblin on this thread, that answer from @pengliheng on a related issue is much cleaner:
https://github.com/nuxt/vue-meta/issues/417#issuecomment-514934337

In short, simply speciry the `MetaInfo` return type on `metaInfo`:
```
...
metaInfo(): MetaInfo {
  return {
    title: 'My title'
  }
}
...
```

**Comment by BonBonSlick** [comment]
```
import Vue                from "vue";
import {MetaInfo}         from "vue-meta";
import {MetaInfoComputed} from "vue-meta/types/vue-meta";

declare module "vue/types/options" {
    interface ComponentOptions<V extends Vue> {
        metaInfo?: MetaInfo | MetaInfoComputed | undefined;
    }
}
...


@Template
@Component<PageMeta>({
                         components: {},
                         mixins:     [],
                         metaInfo(): MetaInfo {
                             return {
                                 title: 'Homepage Title',
```

does not work

**Comment by BonBonSlick** [comment]
Please add documentation on this how to add your package to typescript project, because issues are outdated. If possible with example.

**Comment by flowck** [comment]
Did the job for me: 

```
@Component({
  metaInfo(this: PostView): MetaInfo {
    return { title: this.pageTitle };
  },
})
export default class PostView extends Vue {
  private currentPost!: IPost;
  
  get pageTitle() {
    return this.currentPost.title;
  }
}
```

1. Set `metaInfo` as a method that receives `this` as an argument, and set the class as its type: `metaInfo(this: YourComponentClassName)`

Source: https://github.com/nuxt/vue-meta/issues/340#issuecomment-683516960

**Comment by electrocnic** [comment]
Just in case someone else is using `vue-cli`:

I needed to add `'vue-meta'` to my `transpileDependencies` (or create this option if it did not exist) in my `vue.config.js` (also create this file if it does not exist):

`vue.config.js`:
```
module.exports = {
  transpileDependencies: ['vue-meta']
}
```

Else, the dependency will not be correctly transpiled by Babel and I got the error
```
error  in ./node_modules/vue-meta/dist/vue-meta.esm-browser.min.js

Module parse failed: Unexpected token (8:7170)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

**Comment by WilliamFalci** [comment]
> Just in case someone else is using `vue-cli`:
> 
> I needed to add `'vue-meta'` to my `transpileDependencies` (or create this option if it did not exist) in my `vue.config.js` (also create this file if it does not exist):
> 
> `vue.config.js`:
> 
> ```
> module.exports = {
>   transpileDependencies: ['vue-meta']
> }
> ```
> 
> Else, the dependency will not be correctly transpiled by Babel and I got the error
> 
> ```
> error  in ./node_modules/vue-meta/dist/vue-meta.esm-browser.min.js
> 
> Module parse failed: Unexpected token (8:7170)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> ```

Im using:
`"vue-meta": "^3.0.0-alpha.9"`
`"vue": "^3.1.2",`

into vue.config.js under module.exports I have:
`transpileDependencies: ['@vue/reactivity','vue-meta'],`

but still I got the same error:

`error  in ./node_modules/vue-meta/dist/vue-meta.esm-browser.min.js

Module parse failed: Unexpected token (8:7170)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders`


how I can fix it?

**Comment by god-of-js** [comment]
This is what worked for me

```
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component({
  name: "Login",
  metaInfo() {
    return {
      title: "Authentication - Login",
      meta: [
        {
          name: "Login",
          content: "Log in to access your Docuvaluate Dashboard",
        },
      ],
    };
  },
})
export default class Login extends Vue {
  APP_NAME: string = process.env.VUE_APP_APP_NAME;
}
</script>


```
