### ISSUE TITLE
Add locale to title meta

### ISSUE THREAD

**Issue by iMomen** [declandewet/vue-meta#152]
Is it available to include a local string to the title meta?
my data object is something like this
`pageTitle: 'Loading... | $t("websiteName")',`

**Comment by akaneru** [comment]
Any update about that? I would need to this functionality. It would fantastic if it will possible.
Working on it by my self I don't have found a solution.

Thank you!

**Comment by Atinux** [comment]
It should work by using `metaInfo` as a function directly.

See i18n example with Nuxt.js: https://github.com/nuxt/nuxt.js/blob/dev/examples/i18n/pages/_lang/index.vue#L13

**Comment by akaneru** [comment]
Thank you for the reply, I've tried like specified in the example but for me still not working!
Best regards

**Comment by fps20only** [comment]
@akaneru Instead of defining metaInfo as an object, define it as a function and access this as usual.

`
export default {
    metaInfo () {
      return {
        title: this.$t("home.title"),
      }
    }
  }
`

[vue-meta FAQ](https://github.com/declandewet/vue-meta#how-do-i-use-component-props-andor-component-data-in-metainfo)

**Comment by akaneru** [comment]
I confirm that your solution works!
Thank you :)

**Comment by bekir-kaplan** [comment]
```
metaInfo() {
    return {
      title: 'Title',
      meta: [
        {
          hid: 'root-description',
          name: 'description',
          content: this.$t('tags.videoConference'),
        },
      ],
    }
  },
```
  
 Above is not working for me, nuxt - vue js static application, configuration file we set ssr to false state.
