### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by pocka** [declandewet/vue-meta#157]
Thanks for this awesome package!

Are there any plans for implementing type definitions for Typescript?

**Comment by Atinux** [comment]
I don't have so much time to add the typing, but I am willing to merge a PR if someone wants to do it :)

**Comment by Raiondesu** [comment]
@Atinux,

Addresed the issue in PR #185

**Comment by Zacaria** [comment]
For the ones who are trying to make it work with Typescript here's how it worked for me:

```
import { MetaInfo } from 'vue-meta';

declare module "vue/types/vue" {
    interface Vue {
        metaInfo(): MetaInfo | (() => MetaInfo)
    }
}

```
