### ISSUE TITLE
work with router meta

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [declandewet/vue-meta#158]
Maybe this was dicussed before but I couldnt find it, but is there a way I can set the titles i want in routes meta, and then get it to vue-meta? Working together with titleTemplate aswell, I'm trying to do with beforeEach router hooks but didn't realized yet

**Comment by Atinux** [comment]
It should work within Component `beforeEach` hook directly, I don't have time to give you an example sorry.

**Comment by waghcwb** [comment]
If someone still needing this

```js
const routes = [
  {
    path: '/some-path',
    name: 'some-name',
    component: SomeComponent,

    meta: {
      title: 'Some cool title'
    }
  }
]
```

```js
metaInfo() {
  return {
    title: this.$route.meta.title
  }
}
```
