### ISSUE TITLE
changed() hook invoked twice

### ISSUE THREAD

**Issue by Antoine-Demailly** [declandewet/vue-meta#159]
I have an issue with the `changed()` hook.

It's called twice on route change:
- First with the good component (where changed() is defined)
- Second with the previous route component

package version: 1.3.1

ps: i define `changed()` only one time

**Comment by bodinsamuel** [comment]
I also experience this "issue".
maybe it's wanted but we should be able to determine which is the current component, maybe with an other params or something.
Right now, I store the current component uid and compare it when I receive the event, which feels not quiet right.

**Comment by Antoine-Demailly** [comment]
I actually try to fix it [here](https://github.com/Antoine-Demailly/vue-meta/commit/9c50dd03d519217daf3c9a34903a72ce572ae308) by prevent changed() hook when component is destroyed.

But it's not really clean

**Comment by Atinux** [comment]
Should work with latest version of vue-meta.

**Comment by atorscho** [comment]
I still have this same issue. 

I have installed the latest version: 1.5.0.
