### ISSUE TITLE
adding link preload functionality

### ISSUE THREAD

**Issue by shershen08** [declandewet/vue-meta#164]
Hello
I've been recently working on a small plugin that simplifies the `<link type="preload" ` functionality.
It enables easier adding script/image/style adding to a page for developer https://github.com/shershen08/vue-preload

Do you think that may be handy to add simmilar functionality via PR in the SSR section?

**Comment by Atinux** [comment]
Hi @shershen08 

Nice plugin!

Actually, you can already add preload scripts by adding `type: 'preload'` into the `link` attribute :)
