### ISSUE TITLE
Add attribute to head

### ISSUE THREAD

**Issue by iamdubx** [declandewet/vue-meta#165]
How to add attribute to actual `head`? Why I can't find no info in Docs? This is stratnge.

```html
 <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
```

**Comment by Atinux** [comment]
This is because `<head>` should not have any attributes: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head (`profile` is deprecated)

**Comment by iamdubx** [comment]
@Atinux what about `<head lang="en">` or `<head prefix: http://ogp.me/ns#>`? It's the common practice.

**Comment by onlyurei** [comment]
@Atinux MDN does say the following:

> Attributes
> This element includes the [global attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes).
> profile 
> The URIs of one or more metadata profiles, separated by white space.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head

Looks like only the special attribute `profile` is mentioned as deprecated.
