### ISSUE TITLE
how use like this "<meta http-equiv='x-ua-compatible' content='IE=edge'>"

### ISSUE THREAD

**Issue by hello-guoguo** [declandewet/vue-meta#170]
when i use it(vue-meta),and my setting:
`{ charset: 'utf-8' },`
` { name: 'viewport', content: 'width=device-width, initial-scale=1' },`
` { http-equiv: 'x-ua-compatiable', content: 'IE=edge' }`

is it right???     no!!!
it's error:
C:\Users\Administrator\Desktop\vue\zt_pc\nuxt.config.js:10
      { http-equiv: 'x-ua-compatiable', content: 'IE=edge' },
            ^
SyntaxError: Unexpected token -

**Comment by tr-text** [comment]
So there's no problem with writing
{'http-equiv':'http-equiv', content:'text/html; charset=UTF-8'}

**Comment by hello-guoguo** [comment]
@tr-text thx,I'm so 'silly!
