### ISSUE TITLE
Server memory leak

### ISSUE THREAD

**Issue by btkostner** [declandewet/vue-meta#173]
Running `vue-meta` with SSR will leak memory on render. I have not tracked down where in the code this occures, but from removing `vue-meta` the package and code I have narrowed it down to vue-meta.

Memory tracked with `memory-usage` package and load tested with Locust. With `vue-meta`:
![screenshot from 2017-12-13 10 14 04](https://user-images.githubusercontent.com/3385679/33952487-28dbb326-dfef-11e7-9e0a-a4db1f1af3fa.png)

Without `vue-meta`:
![screenshot from 2017-12-13 10 13 45](https://user-images.githubusercontent.com/3385679/33952503-37221da8-dfef-11e7-9059-72d94d584706.png)

**Comment by BorjaRafols** [comment]
Wow... I'll check this too, I have included vue-meta and many more packages an I'm experiencing the same as you. Let me test this

**Comment by Atinux** [comment]
Hi,

It would be really nice of you to help me track where this comes from, I have a lot of work already with Nuxt.js.

@BorjaRafols  @btkostner

**Comment by Atinux** [comment]
@btkostner @BorjaRafols Could you provide me a reproduction link and how you can have these nice stats about memory?

**Comment by btkostner** [comment]
@Atinux the memory graphs where made with `memory-usage` while running `Locust` (a python app) for load testing.

Give me a bit, and I'll try making a bare bones repo to reproduce this

**Comment by hvalcourtSerdy** [comment]
Hi, you should also read this : https://forum.vuejs.org/t/tracking-down-memory-leak-on-the-server/8802/17 . In his case, it's not vue-meta at the end of the debugging.

**Comment by btkostner** [comment]
Looking at this, it seems it was fixed in some package update. I'm trying to track down what package, but it's not present with _current_ up to date packages.

**Comment by btkostner** [comment]
Closing as it seems this problem was resolved somewhere else. If you are still experiencing this problem, remove your `node_modules` folder and re-run `npm i`.

**Comment by BorjaRafols** [comment]
Yes, I can confirm, memory leak in my case was coming from elsewhere. Sorry for alarms
