### ISSUE TITLE
Metadata not displaying when pushing to production

### ISSUE THREAD

**Issue by 20chix** [declandewet/vue-meta#175]
Hi 

I'm following your repo for simple description and title of the page, the title works perfectly in development and production.

But when i use tool that check my meta tags nothing comes up.

Help please

![capture](https://user-images.githubusercontent.com/15612171/34060237-b4cbb29a-e1da-11e7-9715-2987897a5c63.PNG)

```
  metaInfo: {
    title: 'Contact us',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { vmid: 'description', name: 'description', content: 'some descriptions here' }
    ]
  }


```

**Comment by MDSLKTR** [comment]
Hello,
Metatags are applied in async batched operations. Depending on the Tool you use to check the site, the metatags might not be applied when the metatags are checked, but a few moments after. Google is afaik able to parse this aynchronously. One way to resolve this would be to use Server Side Rendering in Vue so the meta tags are already written on the server side when the page gets delivered to the client.

Regards,
Simon

**Comment by 20chix** [comment]
Hi 

Thanks for quick response, 

That’s that mean I won’t be able to index my page into google with right description and title unless I do server side rendering? 

Because I can see the right title into google but the description are not there , it uses the text from the page not the one I wrote specifically for meta tags description.

Thanks I’m advance

**Comment by MDSLKTR** [comment]
Hi again,

maybe this article helps: https://www.google.de/amp/s/www.simoahava.com/amp/seo/dynamically-added-meta-data-indexed-google-crawlers/

It‘s definitly harder to parse dynamically added metatags for crawlers, but apparently google can do it (maybe it takes some time..). Only way to be 100% sure that all crawlers can read it, is to serve the metatags from static html or with SSR rendered html.

Regards,
Simon

**Comment by 20chix** [comment]
Hi 

Thanks for article that was really useful, what you think is the best way to add description and title for search engines like google? Is it to use SSR? If so do you have a simple example ? Because the one from the README is a bit confusing 

Thanks In advance

**Comment by MDSLKTR** [comment]
Hello,

welp the example here in the docs is pretty straight forward though. This is a pretty good starting point in my opinion since it just works without having to understand all parts: https://github.com/vuejs/vue-hackernews-2.0. But yeah in general i would recommend you do as much as you can on the server. Also the safest path for getting you're site crawled correctly.

Regards,
Simon
