### ISSUE TITLE
IE11 Fix or Polyfill

### ISSUE THREAD

**Issue by mathieumagalhaes** [declandewet/vue-meta#178]
I would like to point out an error I'm seeing on IE11 and below.
IE11 does not support **Array.prototype.includes**

As Array.prototype.includes only differs in the use-case of an array including NaN values,
I would suggest changing it to 
```Array.indexOf(...) !== -1```

In the files
- src/client/updaters/updateTags.js
- src/server/generators/tagGenerator.js

Second option would be adding a Polyfill which in this case might be overkill to be honest

**Comment by Atinux** [comment]
Hi @mathieumagalhaes 

Nice catch, I just made a fix and will publish the patch today: https://github.com/declandewet/vue-meta/commit/a9ba6f5aba9d5f6c7f8c166495444a2c0247688a
