### ISSUE TITLE
Vue Component Class support

### ISSUE THREAD

**Issue by arthurvasconcelos** [declandewet/vue-meta#181]
Hi I use [vue-class-component](https://github.com/vuejs/vue-class-component) in my project and I am trying to use props and data with vue-meta but the method **metaInfo()** is not working in this scenario.

**Comment by salvadornico** [comment]
Hi, how did you use it in your component? I'm able to use props & data in my title (though Typescript throws an error about 'post' not existing on type Vue, so I had to set `noImplicitThis: false` in my tsconfig.json)

```
@Component({
	metaInfo() {
		return {
			title: this.post.title,
		}
	}
})
```

**Comment by Raiondesu** [comment]
I also struggle with this one.
@declandewet, please

**Comment by arthurvasconcelos** [comment]
I managed to solve this. I made a custom decorator for myself:

**decorators.js**
```javascript
import { createDecorator } from 'vue-class-component';

export const Meta = createDecorator((options, key) => {
    options['metaInfo'] = options.methods[key];
});
```
Using it like this:

**my-component.js**
```javascript
import Vue from 'vue';
import { Component } from 'vue-property-decorator';
import { Meta } from 'path/to/decorators';

@Component({
    mixins: [
        require('./my-component-template.vue').default
    ]
})
export default class MyComponent extends Vue {
    @Meta
    myMetaConfig() {
        return {
            title: 'My custom meta config'
        };
    }
}
```

**Comment by Atinux** [comment]
Awesome!

**Comment by texdc** [comment]
@Atinux Shouldn't the decorator be included in the this library?
@arthurvasconcelos would you be willing to open an PR?

**Comment by pkjy** [comment]
@arthurvasconcelos got `Object is possibly 'undefined'.ts(2532)` error.
![image](https://user-images.githubusercontent.com/14119424/50825882-2a1a9f80-1375-11e9-9e6f-ad50b009fee7.png)


just add `undefined` check
``` js
export const Meta = createDecorator((options, key) => {
    options['metaInfo'] = options.methods[key];
});
```
to
``` js
export const Meta = createDecorator((options, key) => {.
    if (!options.methods) return
    options['metaInfo'] = options.methods[key];
});
```
