### ISSUE TITLE
How to pre-fill `to` and `title` fields of a mail client?

### ISSUE THREAD

**Issue by AlexLomm** [declandewet/vue-meta#182]
Is there a way to specify `to` and `title` fields of a mailing client to be pre-filled?

**Comment by manniL** [comment]
This is not related to vue-meta :thinking: 

` <a href="mailto:test@example.com?subject=Example%20Subject&body=test">here</a>`

**Comment by AlexLomm** [comment]
Sorry, please ignore this question :rofl:
