### ISSUE TITLE
How do I add an ID attribute to a script tag?

### ISSUE THREAD

**Issue by jordanranson** [declandewet/vue-meta#184]
I'm trying to use vue-meta to add the Agile CRM tracking code, but the snippet has an ID in the script tag:

```
<script id="_agile_min_js" async type="text/javascript" src="https://yourdomain.agilecrm.com/stats/min/agile-min.js"> </script>
</script>
```

I can't see a way to add the ID to the tag in the documentation in the README, unless I'm missing something.

Is there a way to do this?

**Comment by jordanranson** [comment]
Nevermind, figured it out.

**Comment by simplenotezy** [comment]
Would be great @jordanranson if you'd cared to share your experience with others who could come in a similar situation :-)
