### ISSUE TITLE
Components without `$el` will cause destroy hook to fail

### ISSUE THREAD

**Issue by elrolito** [declandewet/vue-meta#187]
https://github.com/declandewet/vue-meta/blob/776ddf62a233079dbd0c90cfdd8f8fc749188fcd/src/shared/plugin.js#L89-L93

Using [vuelidate](https://github.com/monterail/vuelidate) creates components that do not have an `$el` property, but still have `_hasMetaInfo` set to `true`, which results in the `setInterval` never being cleared. There may be other plugins that create similar components.

Changing the line to `if (this.$el && this.$el.offsetParent !== null) return` would resolve this issue.

**Comment by Atinux** [comment]
Thank you for reporting this issue, it's fixed by #196

**Comment by elrolito** [comment]
Cool, thanks. Glad I could help. 👍
