### ISSUE TITLE
What's the purpose of noscript tag of vue-meta?

### ISSUE THREAD

**Issue by waghcwb** [declandewet/vue-meta#217]
What's the main purpose of `noscript` tag in this project? If the user disable the Javascript, `vue` will not load, and `vue-meta` too..

I'm not experienced with Vue, I'm just asking about it..

**Comment by waghcwb** [comment]
@ricardovigatti,

Of course. When I opened this issue I didn't know about [Server Side Rendering](https://ssr.vuejs.org), so if your project uses SSR the HTML template will come rendered from the backend.

**Comment by ricardovigatti** [comment]
Nice, thanks for your message.

We aren't using SSR at the moment and I'm facing issues trying to properly use Facebook's OpenGraph tags. Guess its similar to this <noscript> tag problem.

Do you think the only way to properly implement those features is using SSR?

**Comment by waghcwb** [comment]
I like to use SSR for SEO purposes, but if you don't want, depending on your project structure you can put the Facebook tags manually on the `index.html` file.

**Comment by ricardovigatti** [comment]
That's true, and it works.. I just forgot to mention that I need to change those tags based on the active route.. Until now, I saw two ways that could handle this: Pre-fetching and SSR, but idk which one will be the ideal choice for me at the moment.

**Comment by waghcwb** [comment]
@ricardovigatti,

What's your project architecture? Was created with [`vue-cli`](https://cli.vuejs.org/)? I think SSR is a good choice, but without knowing the scope it's hard to say.

**Comment by ricardovigatti** [comment]
vue-cli, yes. But it's a PHP project, we don't have a node server yet. Guess SSR needs one, right?

**Comment by waghcwb** [comment]
@ricardovigatti,

No, you don't need a node server, you need _any_ backend server. You can use the same logic of a node server in your PHP server.

**Comment by waghcwb** [comment]
@ricardovigatti,

Sorry, I was mixing things :sweat_smile:

You can use Vue frontend with any backend, but SSR needs a Javascript engine. Luckily, people already did the SSR implementation for PHP
https://packagist.org/packages/spatie/server-side-rendering
