### ISSUE TITLE
Option to set titleTemplate once for whole app 

### ISSUE THREAD

**Issue by shershen08** [declandewet/vue-meta#236]
For not complex use cases when plugin is used only for setting title of the rendered vue-router page, that would be nice to set titleTemplate once in the config phase as so: 

```
Vue.use(Meta, {
  titleTemplate: (titleChunk) => `${titleChunk} - ${config.APP_VERSION}`,
  // other configs
})
```

and later on separate routes/pages just use `metaInfo.title` property to pass title

```
export default {
  name: 'LoginPage',
  metaInfo: {
    title: 'Login'
  },
```
and 
```
export default {
  name: 'SearchResults',
  metaInfo: {
    title: 'Search results'
  },
```

**Comment by issaTan** [comment]
Maybe you can set the template in `App.vue`? Just like this: https://github.com/declandewet/vue-meta#step-3-start-defining-metainfo

**Comment by shershen08** [comment]
Yes, works like a charm
@issaTan Thanks!
