### ISSUE TITLE
How to make prev/next tags (conditional) for pagination?

### ISSUE THREAD

**Issue by canyoudev** [declandewet/vue-meta#238]
For SEO pagination I need next/prev tags. The thing is, they must be rendered differently on other routes. 

For example, I have this

```js
{ rel: 'prev', href: `${this.$store.getters.baseUrl + this.$route.path}?page=${this.currentPage - 1}` },
{ rel: 'next', href: `${this.$store.getters.baseUrl + this.$route.path}?page=${this.currentPage + 1}` },
```

This is working fine for all pages beside first one and last one. On first page I don't need `prev` and on last one I don't need `next` tag. 

How to solve this? have no idea. Please help!

**Comment by manniL** [comment]
You can add them on **component-level** with conditions :relaxed: 

```js

{
 computed: {
   paginationLinks () {
      const nextUrl = { rel: 'next', href: this.nextUrl }
      const previousUrl = { rel: 'prev', href: this.previousUrl }

      return [nextUrl, previousUrl].filter(({ href }) => !!href)
    }
  },
  head () {
    return {
      link: this.paginationLinks
    }
  }
}
