### ISSUE TITLE
Add support for merging mixins

### ISSUE THREAD

**Issue by adrienbaron** [declandewet/vue-meta#261]
A few libraries in Nuxt (vue i18n, Vuetify) uses mixins for Vue Meta.
Vue Meta for now doesn't support Mixins merging, resulting in conflicts when using both those libraries at the same time in Nuxt.

I will try to add support for mixins merging and do a pull request as offered by @Atinux 

See: https://github.com/nuxt/nuxt.js/issues/3846

**Comment by adrienbaron** [comment]
I managed to add the feature this way:
- I register the optionMergeStrategies to be the same as `created`, meaning options get merged in an Array
- I added the ability to `getComponentOption` to merge those array of options

Two things I had to do that I'm not sure about:
- I had to change the test `allows for a custom array merge strategy` in `getComponentOption`
This tests was passing an Array as a top level option object, but we now assume that arrays at top levels means that we should merge it's content. So I changed the test to pass an object containing the array instead:
```js
foo: [
  { name: 'flower', content: 'rose' }
]
```

became:
```js
foo: {
  flowers: [
    { name: 'flower', content: 'rose' }
  ]
}
```

- I had to manually register the optionMergeStrategies in the test of `getMetaInfo`
This is to allow testing the merging of mixins in this test
See: https://github.com/adrienbaron/vue-meta/commit/ad4d61c38ff8e83cf4d933b961cc8875e1e22f60#diff-aad47313d609c07f1d9316d0918465a4R24

If those changes are OK I'll create the pull request :)

**Comment by bdrtsky** [comment]
I am not sure, this option is working or not? I am trying to use mixin with `head` but it's not working

**Comment by adrienbaron** [comment]
This PR was reverted because it was breaking other things (see: https://github.com/nuxt/vue-meta/issues/269)

**Comment by philefstat** [comment]
I just wanted to share for others who come across this issue, who are using the `head()` function in a mixin - you can use the following to merge the result of the mixin:

```js
let strategies = Vue.config.optionMergeStrategies
strategies.head = strategies.data
```

**Comment by Gvade** [comment]
> I just wanted to share for others who come across this issue, who are using the `head()` function in a mixin - you can use the following to merge the result of the mixin:
> 
> ```js
> let strategies = Vue.config.optionMergeStrategies
> strategies.head = strategies.data
> ```

@philefstat At what place do you reassign the merge strategy? I can't use  `vue.config` in `nuxt.config.js` as it doesn't accept function.
