### ISSUE TITLE
Style and Script not converted right

### ISSUE THREAD

**Issue by Zwaen91** [declandewet/vue-meta#33]
In version 0.5.2 the style and script are not converted how they should.

```
metaInfo: {
        titleTemplate: 'Shop Admin | %s',
        title: 'Dashboard',
        style: [
            { cssText: '.foo { color: red }', type: 'text/css' }
        ],
        script: [
            { innerHTML: 'console.log("Foo");', type: 'text/javascript' }
        ]
 }
```
```
<style csstext=".foo { color: red }" type="text/css" data-vue-meta="true"></style>
<script innerhtml="console.log(&amp;quot;Foo&amp;quot;);" type="text/javascript" data-vue-meta="true"></script>
```

**Comment by declandewet** [comment]
Hi @Zwaen91 - I think I know what the issue is. Could you add `__dangerouslyDisableSanitizers: ['script']` to your `metaInfo` and see if it works?

**Comment by Zwaen91** [comment]
It works

**Comment by jeerbl** [comment]
Hi

Does not work for me. `innerHTML` is still attached to the `script` element as an attribute. I opened #58 and PR #59 to fix this.

@Zwaen91 what version were you using?

Cheers
Jerome
