### ISSUE TITLE
Doesn't work with vue-router + ssr

### ISSUE THREAD

**Issue by mehwww** [declandewet/vue-meta#42]
It seems before the vue root instance `mounted`, its `$children` will be an empty array, so `getComponentOption` won't work properly cause we don't 'mount' instance in server side.

Anyone has the same issue ?

**Comment by fenivana** [comment]
+1. won't work with nested routes.

**Comment by Atinux** [comment]
Could you provide a https://gomix.com example to show this behaviour please?

**Comment by mehwww** [comment]
Sorry it's my mistake using this lib wrong way. 😔

my code:
```javascript
const context = {url}
const renderStream = renderer.renderToStream(context)
const html = ((meta) => ...)(context.meta.inject())

renderStream.on('data', () => ...)
```

correct way:
```javascript
const context = {url}
const renderStream = renderer.renderToStream(context)
let html

renderStream.once('data', () => html = ((meta) => ...)(context.meta.inject()))
renderStream.on('data', () => ...)
```

@fenivana Maybe you meet some real bug but I will close this issue now.
