### ISSUE TITLE
beforeMount is calling server side

### ISSUE THREAD

**Issue by codingfriend1** [declandewet/vue-meta#51]
I'm not sure if this is an issue with your library, my setup or Vue itself.

But 

```
beforeMount: function beforeMount () {
      var this$1 = this;

      // batch potential DOM updates to prevent extraneous re-rendering
      batchID = batchUpdate(batchID, function () { return this$1.$meta().refresh(); });
    }
```

this is being called server side. Even this.$isServer comes back true and it's throwing a document no found error. Technically I don't think beforeMount is supposed to run server side so this may be an issue with Vue.

**Comment by Atinux** [comment]
Hi @codingfriend1 

I am sure that `beforeMount` is not called on server-side, there may be an issue in your code directly.
