### ISSUE TITLE
__dangerouslyDisableSanitizers causing errors

### ISSUE THREAD

**Issue by john-ko** [declandewet/vue-meta#54]
Hello, I'm new to vuejs and vue-meta

the issue is I am running into some errors on the client side and I have a working hack, but would like some insights on how to properly handle these errors

# the problem
I think that the vue-meta thinks `__dangerouslyDisableSanitizers` and its value `['script']` are properties and tries to continually traverse into the `['script']` array which then causes the string `'script'` into an array.
```
__dangerouslyDisableSanitizers ["script"]
0 s
1 c
2 r
3 i
4 p
5 t
```

some background, I am using SSR and ran into this issue, however it is reproducible on the examples as well 

## Here are the Errors (chrome inspector)

```
updateTags.js?8526**:37 Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.
    at http://localhost:8080/__build__/basic.js:9274:26
    at Array.forEach (native)
    at updateTags (http://localhost:8080/__build__/basic.js:9259:12)
    at http://localhost:8080/__build__/basic.js:9151:67
    at Array.forEach (native)
    at http://localhost:8080/__build__/basic.js:9133:30
    at updateClientMetaInfo (http://localhost:8080/__build__/basic.js:9166:9)
    at Vue$3.refresh (http://localhost:8080/__build__/basic.js:9083:49)
    at http://localhost:8080/__build__/basic.js:9811:31
    at http://localhost:8080/__build__/basic.js:9042:5
``` 

## heres the code from `examples/basic/app.js`

```js
import Vue from 'vue'
import VueMeta from 'vue-meta'

Vue.use(VueMeta)

new Vue({
  template: `
    <div id="app">
      <h1>Basic</h1>
      <p>Inspect Element to see the meta info</p>
    </div>
  `,
  metaInfo: () => ({
    title: 'Basic',
    titleTemplate: '%s | Vue Meta Examples',
    htmlAttrs: {
      lang: 'en',
      amp: undefined
    },
    script: [
      { innerHTML: '{ "@context": "http://schema.org" }', type: 'text/javascript' }
    ],
    __dangerouslyDisableSanitizers: ['script']

  })
}).$mount('#app')
```

### updateClientMetaInfo.js
~ line 36 i added `case '__dangerouslyDisableSanitizers':`

```
case 'titleChunk':
case 'titleTemplate':
case 'changed':
case '__dangerouslyDisableSanitizers':
  break
// catch-all update tags
default:
...
```

### getMetaInfo.js
~ line 101 i added 
`escaped[key] = val;`
`if (key === '__dangerouslyDisableSanitizers') return escaped;`

```
const isDisabled = ref && ref.indexOf(key) > -1
const val = info[key]

escaped[key] = val;
if (key === '__dangerouslyDisableSanitizers') return escaped;

if (!isDisabled) {
  if (typeof val === 'string') {
    escaped[key] = escapeHTML(val)
...
```

open to any comments
thanks!

**Comment by surmon-china** [comment]
Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.

I have the same problem

**Comment by john-ko** [comment]
@surmon-china you can try the following hack as a workaround or use [WEBuster/vue-meta](https://github.com/WEBuster/vue-meta)

**Comment by surmon-china** [comment]
@john-ko 
thanks:)
 i will try

**Comment by zweizeichen** [comment]
As you can use JSON for embedding microdata (which I would guess is the main use case for disabling script sanitization), entirely skipping sanitization for scripts should not be necessary in that case. Maybe allow to pass a plain JS object in case you want to use JSON+LD which then gets serialized to JSON and put into an appropriate tag.

**Comment by ooxif** [comment]
I have the same problem
FYI: my workaround https://gist.github.com/ooxif/bba97fb194a8e982b109422050cd3783

**Comment by Atinux** [comment]
It's now fixed in the last version :)
