### ISSUE TITLE
imports not working on Meteor

### ISSUE THREAD

**Issue by laosb** [declandewet/vue-meta#55]
*Reproduction:*

```
meteor create test-app
cd test-app
meteor add akryum:vue-component
npm i vue vue-meta --save
npm i
meteor
```

Then import vue-meta on the client-side, results in:

![image](https://cloud.githubusercontent.com/assets/2545261/22549392/120e233c-e986-11e6-845e-3bf43827d50b.png)

akryum:vue-component should not be related to this problem though.

**Comment by laosb** [comment]
Cross posted to akryum:vue-component at Akryum/meteor-vue-component#111

**Comment by Atinux** [comment]
I'm closing this issue since it seems related to Meteor itself.
