### ISSUE TITLE
when add option like '__dangerouslyDisableSanitizers' in Nuxt.js , something is wrong like 'Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.'

### ISSUE THREAD

**Issue by zhouyu1993** [declandewet/vue-meta#73]
[vue-meta in nuxt](https://forum.vuejs.org/t/inline-script-in-head-gets-mangled-when-routing-to-a-new-page-nuxt/7992)

`
script: [
    {innerHTML: "(function(h){h.className=h.className.replace('no-js','js')})(document.documentElement)"}
],
__dangerouslyDisableSanitizers: ["script"], // because of the inner quotes
`

From one route to another route, something is wrong like 'Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.'

line 786:

`
newElement.setAttribute(attr, value);
`

**so we fix it like this:**

![image](https://cloud.githubusercontent.com/assets/13276621/24492013/62bb684c-155c-11e7-9868-5851f9202b9c.png)

**Comment by Atinux** [comment]
Fixed with the last release.
