### ISSUE TITLE
document on ssr = true is not defined

### ISSUE THREAD

**Issue by dohomi** [declandewet/vue-meta#74]
Hello 

I'm using nuxt and would like to know if its possible that there is currently a bug in vue-meta regarding of a document call on SSR: vue-meta line 825:
```
function _updateClientMetaInfo (options) {
  if ( options === void 0 ) options = {};

  var ssrAttribute = options.ssrAttribute;

  /**
   * Performs client-side updates when new meta info is received
   *
   * @param  {Object} newInfo - the meta info to update to
   */
  return function updateClientMetaInfo (newInfo) {
    var htmlTag = document.getElementsByTagName('html')[0];
```
```
  var htmlTag = document.getElementsByTagName('html')[0];
                  ^

ReferenceError: document is not defined
```

If ssrAttribute is set, and the server tries to render, vue-meta throws error. Any idea if this intend to work like this? I posted this on nuxt as well: https://github.com/nuxt/nuxt.js/issues/449
Thanks

**Comment by JiriChara** [comment]
Not sure if related, but you can also have a look on my latest comment https://github.com/nuxt/nuxt.js/issues/449#issuecomment-290976803

**Comment by Atinux** [comment]
Should be fixed with the last version (I will update nuxt.js soon)
