### ISSUE TITLE
title.text() is empty

### ISSUE THREAD

**Issue by Sleashe** [declandewet/vue-meta#78]
Hi Guys,

I recently installed vue-meta to manage my titles, metas etc. This plugin is excellent so thanks a lot !
However I'm facing a few issues while trying to make it work with SSR.

I started my project from the well known official hackernews2 template. I precisely followed vue-meta plugin instructions regarding SSR but when I log context.meta.inject().title.text() when rendering on server, I always get: 
`<title data-vue-meta="true"></title>`

Since the code from hackernews was a bit different, here's what I did : 
1. Added Vue.use(Meta) inside `app.js`
2. Added `const meta = app.$meta()` and `context.meta = meta` inside `server-entry.js`
3. Added some metaInfo inside app.vue component
3. Updated the code inside `server.js` to this (I don't know if its the best way):
```
  let context = { url: req.url }
  let stream = renderer.renderToStream(context)
  stream.on('error', errorHandler)
  stream.on('end', () => console.log(`whole request: ${Date.now() - s}ms`))
  stream.on('pipe', (chunk) => {
    const {
      title, htmlAttrs, bodyAttrs, link, style, script, noscript, meta
    } = context.meta.inject()
    console.log(title.text()) // Here's where I always got <title data-vue-meta="true"></title>
    chunk.head = chunk.head.replace(/<title>(.*?)<\/title>/, title.text()) //Obviously, regarding the previous line, the replaced title contains <title data-vue-meta="true"></title>...
    chunk.head = chunk.head += meta.text() // A test to append meta from vue-meta at the end of the header. Didn't try it yet
  })
  stream.pipe(res)
```

Are you facing the same issue ? What am I doing wrong ?

Thanks a lot in advance,

**Comment by Atinux** [comment]
Hi @Sleashe 

Could you share your repo so we can try to help you to debug?

**Comment by ptitkiller** [comment]
Hi, all
I use https://github.com/vuejs/vue-hackernews-2.0. I config same @Sleashe and same issue.
Thanks a lot in advance.
