### ISSUE TITLE
When I create another new vue instance

### ISSUE THREAD

**Issue by lc60005457** [declandewet/vue-meta#85]
for example:

```
import Vue from 'vue';
import VueMeta from 'vue-meta';

Vue.use(VueMeta);

new Vue({
    el: '#app',
    metaInfo: { ... }
});

new Vue({
    el: '#anoter',
});
```

When another instance changed, like: `beforeCreate`、`created `、`beforeMount `、`destroyed `，document's meta will be clean.

VueMeta should be used for only one vue instance.

Another new vue instance maybe from other people's vue plugin.

**Comment by Atinux** [comment]
Hi @lc60005457 

I am sorry but this is a choice made by @declandewet and I don't think this behaviour will change.
