### ISSUE TITLE
Error: head script dangerouslyDisableSanitizers

### ISSUE THREAD

**Issue by wargt** [declandewet/vue-meta#87]
Hello

I need insert google tag manager

```
head: {
  script: [
    //googletagmanager
    { innerHTML: "some script" },
  ],
  __dangerouslyDisableSanitizers: ['script']
}
```

when i change page (this.$router.push())

I have error Exeption

![](https://cloud.githubusercontent.com/assets/3066246/25278691/d5512b2e-26ac-11e7-8fdc-a6bfedecb452.png)

![](https://cloud.githubusercontent.com/assets/3066246/25278707/e3bc8118-26ac-11e7-9e42-e545b8966b22.png)

Do you can to help me?

**Comment by john-ko** [comment]
see #54 or #73

**Comment by Atinux** [comment]
Closing for duplication.
