### ISSUE TITLE
Function-style metaInfo broken with keep-alive

### ISSUE THREAD

**Issue by Eiskis** [declandewet/vue-meta#95]
When I use vue-meta with vue-router and `<keep-alive>`, I can't reliably use the function-style metaInfo.

I have two pages in my application, with the following in their component definitions:

```js
// Page one
...
metaInfo: {
	title: 'Hello world!'
},
...

// Page 2
...
metaInfo: function () {
	return {
		title: 'Route name: ' + this.$route.name
	};
},
...
```

When I load my application and enter page one, I will see "Hello world!" as the page title. When I switch to page 2, I will see something like "Route name: pageTwoRouteName" as expected. However when I then switch back to page one, the page title is something like "Route name: pageOneRouteName". (The route names are what I have defined in my route configuration.)

It seems that when using a function to return the values for `metaInfo`, [vue-meta starts $watching for the changes](https://github.com/declandewet/vue-meta/blob/master/src/shared/plugin.js#L55) but never stores or calls the `unwatch` callback that would stop listening to the changes and writing, in my case, a new title for the component that has been transitioned out and deactivated but is still alive in the background.

If this is the case then I suspect similar unexpected results happen in any situation where components that use function-style metaInfo are used for a component that is not destroyed when navigating away from them, so it's not vue-router-specific issue even if it's probably the most common use case.

I can work on a PR later on but maybe someone can confirm if this is what's actually happening. If so, maybe just adding the unwatch callbacks to `deactivated` and `beforeDestroy`  will do the trick.

**Comment by Atinux** [comment]
It would be indeed awesome if could create a PR to check if the component is `deactivated` to not watch it.

**Comment by Super-Meng** [comment]
when keep-alive,

**Comment by jorngeorg** [comment]
Having this problem too. When using keep-alive the meta tags for that view will stay in the DOM. When navigating instead of updating them new ones are added. 

Any ideas for strategies to avoid / circumvent this?

**Comment by Atinux** [comment]
It should be fixed with last version of vue-meta

**Comment by laoyoufen** [comment]
this bug has not fix yet
